name: levenshtein
version: 1.0.0
author: Conrad Kleinespel <conradk@conradk.com>
homepage: https://github.com/conradkleinespel/levenshtein-dart
description: An implementation of the Levenshtein distance algorithm
dependencies:
  unittest: "0.9.3"
