name: levenshtein
version: 1.0.2
author: Conrad Kleinespel <conradk@conradk.com>
description: An implementation of the Levenshtein distance algorithm
homepage: https://github.com/conradkleinespel/levenshtein-dart
dev_dependencies:
  test: any
